version: '3'

services:
  payload:
    # Usamos la imagen optimizada para devcontainers. 
    # Facilita el mapeo de usuarios UID/GID sin depender del IDE.
    image: ubuntu:24.04
    volumes:
      - .:/home/node/app:cached
    working_dir: /home/node/app
    # IMPORTANTE: Mantiene el contenedor vivo para que puedas entrar por CLI.
    command: sleep infinity
    depends_on:
      - postgres
    # Forzamos que corra como el usuario 'node' para evitar archivos creados como root
    ports:
      - '3000:3000'

  postgres:
    restart: always
    image: postgres:18
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: josue
      POSTGRES_DB: josue
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pgdata:
