version: '3'
services:
  payload:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'

    
  
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: josue
      POSTGRES_DB: josue
      POSTGRES_HOST_AUTH_METHOD: trust

        
    
volumes:
  pgdata:
  node_modules:
