version: '3'
services:
  payload:
    image: node:22-slim
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - /home/chamba/Desktop/js/websitePayload:/home/node/websitePayload
      - /home/chamba/Desktop/js/tailwindShadPayload:/home/node/tailwindShadPayload
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: josue
      POSTGRES_DB: josue
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pgdata:
  node_modules:
