version: '3'
services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: josue
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -v ON_ERROR_STOP=1 -tAc \"SELECT 1 FROM __restore_healthcheck LIMIT 1\" >/dev/null"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 2m
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/backup_20260105_153850.dump:/dump/backup_20260105_153850.dump:ro
      - ./db/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro
    networks:
      - db_network

  payload:
    image: urgosxd7/payload-cms:latest
    #ports:
    #  - '3000:3000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      # Conecta el servicio payloaubd a la red externa para comunicarse con el proxy
      - proxiable
      # Conecta el servicio payload a la nueva red interna para comunicarse con la base de datos
      - db_network
      - red-compartida
  
volumes:
  pgdata:

networks:
  # Define la red externa existente para la comunicación con el proxy
  proxiable:
    external: true
    name: proxiable # Asegúrate de que este nombre coincida exactamente con tu red externa

  # Define una nueva red bridge interna para la comunicación entre la aplicación y la base de datos
  db_network:
    driver: bridge
    # Docker Compose creará y gestionará esta red automáticamente
  red-compartida:
    external: true      # <--- ¡ESTO ES LO IMPORTANTE!
    name: red-compartida # Asegura que busque el nombre exacto
