version: '3'
services:
  
  postgres:
    restart: always
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword

  payload:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
volumes:
  pgdata:
