apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    uid: tempo
    isDefault: false
    editable: true
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: tourism-events
      tracesToLogs:
        datasourceUid: loki
        tags: ['traceId', 'spanId']
        lokiSearch: true

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    uid: loki
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceId":"(\w+)"'
          url: '$${__value.raw}'

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    uid: prometheus
    isDefault: true
    editable: true
