import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_pages_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum__pages_v_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__pages_v_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum_tours_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_tours_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum__tours_v_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__tours_v_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum_posts_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_posts_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum__posts_v_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__posts_v_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum_tou_p_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_tou_p_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum__tou_p_v_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__tou_p_v_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum_pac_p_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum_pac_p_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  CREATE TYPE "public"."enum__pac_p_v_blocks_grid_images_block_title_tag" AS ENUM('h1', 'h2', 'h3', 'h4', 'h5', 'h6');
  CREATE TYPE "public"."enum__pac_p_v_blocks_grid_images_block_title_size" AS ENUM('small', 'medium', 'large', 'xlarge');
  ALTER TABLE "pages_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "pages_blocks_grid_images" ADD COLUMN "block_title_tag" "enum_pages_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "pages_blocks_grid_images" ADD COLUMN "block_title_size" "enum_pages_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "pages_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "pages_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "_pages_v_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "_pages_v_blocks_grid_images" ADD COLUMN "block_title_tag" "enum__pages_v_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "_pages_v_blocks_grid_images" ADD COLUMN "block_title_size" "enum__pages_v_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "_pages_v_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "_pages_v_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "tours_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "tours_blocks_grid_images" ADD COLUMN "block_title_tag" "enum_tours_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "tours_blocks_grid_images" ADD COLUMN "block_title_size" "enum_tours_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "tours_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "tours_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "_tours_v_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "_tours_v_blocks_grid_images" ADD COLUMN "block_title_tag" "enum__tours_v_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "_tours_v_blocks_grid_images" ADD COLUMN "block_title_size" "enum__tours_v_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "_tours_v_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "_tours_v_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "posts_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "posts_blocks_grid_images" ADD COLUMN "block_title_tag" "enum_posts_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "posts_blocks_grid_images" ADD COLUMN "block_title_size" "enum_posts_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "posts_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "posts_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "_posts_v_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "_posts_v_blocks_grid_images" ADD COLUMN "block_title_tag" "enum__posts_v_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "_posts_v_blocks_grid_images" ADD COLUMN "block_title_size" "enum__posts_v_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "_posts_v_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "_posts_v_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "tou_p_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "tou_p_blocks_grid_images" ADD COLUMN "block_title_tag" "enum_tou_p_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "tou_p_blocks_grid_images" ADD COLUMN "block_title_size" "enum_tou_p_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "tou_p_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "tou_p_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "_tou_p_v_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "_tou_p_v_blocks_grid_images" ADD COLUMN "block_title_tag" "enum__tou_p_v_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "_tou_p_v_blocks_grid_images" ADD COLUMN "block_title_size" "enum__tou_p_v_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "_tou_p_v_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "_tou_p_v_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "pac_p_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "pac_p_blocks_grid_images" ADD COLUMN "block_title_tag" "enum_pac_p_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "pac_p_blocks_grid_images" ADD COLUMN "block_title_size" "enum_pac_p_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "pac_p_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "pac_p_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';
  ALTER TABLE "_pac_p_v_blocks_grid_images" ADD COLUMN "block_title_title_text" varchar;
  ALTER TABLE "_pac_p_v_blocks_grid_images" ADD COLUMN "block_title_tag" "enum__pac_p_v_blocks_grid_images_block_title_tag" DEFAULT 'h2';
  ALTER TABLE "_pac_p_v_blocks_grid_images" ADD COLUMN "block_title_size" "enum__pac_p_v_blocks_grid_images_block_title_size" DEFAULT 'medium';
  ALTER TABLE "_pac_p_v_blocks_grid_images" ADD COLUMN "block_title_text_color" varchar DEFAULT '#2970B7';
  ALTER TABLE "_pac_p_v_blocks_grid_images" ADD COLUMN "block_title_underline_color" varchar DEFAULT '#EFBA06';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "pages_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "pages_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "pages_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "pages_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "_pages_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "_pages_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "_pages_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "_pages_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "_pages_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "tours_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "tours_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "tours_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "tours_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "tours_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "_tours_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "_tours_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "_tours_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "_tours_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "_tours_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "posts_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "posts_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "posts_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "posts_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "posts_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "_posts_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "_posts_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "_posts_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "_posts_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "_posts_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "tou_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "tou_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "tou_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "tou_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "tou_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "_tou_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "_tou_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "_tou_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "_tou_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "_tou_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "pac_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "pac_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "pac_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "pac_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "pac_p_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  ALTER TABLE "_pac_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_title_text";
  ALTER TABLE "_pac_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_tag";
  ALTER TABLE "_pac_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_size";
  ALTER TABLE "_pac_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_text_color";
  ALTER TABLE "_pac_p_v_blocks_grid_images" DROP COLUMN IF EXISTS "block_title_underline_color";
  DROP TYPE "public"."enum_pages_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum_pages_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum__pages_v_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum__pages_v_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum_tours_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum_tours_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum__tours_v_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum__tours_v_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum_posts_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum_posts_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum__posts_v_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum__posts_v_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum_tou_p_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum_tou_p_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum__tou_p_v_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum__tou_p_v_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum_pac_p_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum_pac_p_blocks_grid_images_block_title_size";
  DROP TYPE "public"."enum__pac_p_v_blocks_grid_images_block_title_tag";
  DROP TYPE "public"."enum__pac_p_v_blocks_grid_images_block_title_size";`)
}
